### ISSUE TITLE
Configure - Starlark Roadmap

### ISSUE THREAD

**Issue by jbedard** [aspect-build/aspect-cli-legacy#59]
### Incremental updates
* Minimal processing when only updating a single directory (ongoing)
  * Starlark `exports` hook for indexing without re-generating rules
* Rule index caching ([part1](https://github.com/bazelbuild/bazel-gazelle/pull/1880))
* IDE plugin or daemon process to manage caching and incremental updates

### Performance (ongoing)
* Concurrency (including: [1893](https://github.com/bazelbuild/bazel-gazelle/pull/1893))
* FS traversal (including: [1166](https://github.com/bazelbuild/bazel-gazelle/issues/1166)/[1908](https://github.com/bazelbuild/bazel-gazelle/pull/1908), [1893](https://github.com/bazelbuild/bazel-gazelle/pull/1893)))
* [x] `.bazelignore` perf ~[1890](https://github.com/bazelbuild/bazel-gazelle/pull/1890)~, ~[1886](https://github.com/bazelbuild/bazel-gazelle/pull/1886)~
* [x] Run all starlark extensions in parallel
* [x] Run all queries (tree-sitter, jq, regex, ...) in parallel

### Requests
* BUILD-generation unit test framework
* .star unit test framework, this may require splitting files so `aspect.register_configure_extension` is not in the file being tested
